import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import {AiFillGithub, AiFillLinkedin, AiOutlineMail,} from 'react-icons/ai';
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

const Contact = () => {
	const [darkMode, setDarkMode] = useState(false);
	return (
	  <div className={darkMode ? 'dark' : ""}>
		  <title>Angel Medina Bustos Portfolio</title>
		  <meta name="description" content="Generated by create next app" />
		  <meta name="viewport" content="width=device-width, initial-scale=1" />
		  <link rel="icon" href="/favicon.ico" />
			<main className=' h-screen overflow-auto bg-cool-white dark:bg-dark-mode'>
				<section className = "">
									{/* ---Nav Bar--- */}
					<div className= 'navbar-sticky top-0'>
        				<nav className='sticky p-10 mb-12 flex justify-between'>
        					<button className=""><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)}/></button>
	  		 	 		<ul>
         	  			<li className='font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-cyan-500 to-csumb'>
              			<a className='p-10 mb-12  justify-between' NavLink to="/" href="/">Home</a>
            			<a className='p-10 mb-12  justify-between' href='https://docs.google.com/document/d/1Q64H-SY_bH4pJIc80D8jP_4Awhr9mzMV1zR2SG9OZto/edit?usp=sharing' target="_blank" rel="noreferrer">Resume</a>
            			<a className='p-10 mb-12  justify-between' NavLink to="/contact" href="/contact">Contact</a>
          	  			</li>
        	  			</ul>
        				</nav>
        			</div>
				</section>

				<div className='grid content-cente justify-center p-13 lg:py-16 py-8 mx-auto max-w-screen-md'> 			
					<form className = "space-y-8" action="https://api.web3forms.com/submit" method="POST">

					<input type="hidden" name="access_key" value="a41fd815-f6d0-457b-90a5-cc6976cfaf5f" />

    					<div className="grid gap-6 mb-6 md:grid-cols-1 w-max">
						<p className='mb-4 text-3xl font-extrabold text-center text-custom dark:text-custom'>Contact Me</p>
        				<div className=''>
            				<label for="email" class="block mb-2 text-sm font-bold text-gray-900 dark:text-custom">Email</label>
            				<input type="email" name="email" placeholder="name@gmail.com" class="bg-gray-50 mb-8 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-dark-mode dark:border-csumb dark:placeholder-gray-400 dark:text-custom dark:focus:ring-blue-500 dark:focus:border-blue-500" required />
						</div>
						<div>
            				<label for="subject" class="block mb-2 text-sm font-bold text-gray-900 dark:text-custom">Subject</label>
            				<input type="subject" name="Subject" placeholder="Subject" class="bg-gray-50 mb-8 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-dark-mode dark:border-csumb dark:placeholder-gray-400 dark:text-custom dark:focus:ring-blue-500 dark:focus:border-blue-500" required />
						</div>
						<div>
            				<label for="first_name" class="block mb-2 text-sm font-bold text-gray-900 dark:text-custom">Message</label>
            				<textarea type="message" id="message" rows="6" name="message" className="bg-gray-50 border w-96 mb-8 border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-dark-mode dark:border-csumb dark:placeholder-gray-400 dark:text-custom dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Your message" required />
        				</div>
						<button type = "submit" class = "py-3 px-5 text-sm font-medium text-center text-cool-white rounded-lg bg-custom sm:w-fit hover:bg-csumb duration-700 ">Send message</button>
						</div>
						<input type="hidden" name="redirect" value="https://web3forms.com/success" />
					</form>
				</div>
			</main>
		</div>
	
	);
	
};



export default Contact;
