import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import {AiFillGithub, AiFillLinkedin, AiOutlineMail,} from 'react-icons/ai';
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>Angel Medina Bustos' Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' h-full overflow-auto bg-cool-white dark:bg-dark-mode'>
      <section className = "">

        {/* ---Nav Bar--- */}
        <div className= 'navbar-sticky top-0'>
        <nav className='sticky p-10 mb-12 flex justify-between'>
        <button className=""><BsFillMoonStarsFill
        onClick={() => setDarkMode(!darkMode)}
        /></button>
        <ul>
          <li></li>
          <li className='font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-cyan-500 to-csumb'>
            <a className='p-10 mb-12  justify-between snap- ' href=''>Home</a>
            {/* scrollToElement = () => this.testRef.current.scrollIntoView(); */}
            {/* <a className='p-10 mb-12  justify-between'  href='#'>Projects</a> */}
            <a className='p-10 mb-12  justify-between' href='https://docs.google.com/document/d/1Q64H-SY_bH4pJIc80D8jP_4Awhr9mzMV1zR2SG9OZto/edit?usp=sharing' target="_blank" rel="noreferrer">Resume</a>
            <a className='p-10 mb-12  justify-between' href="https://mail.google.com/mail/u/0/#inbox?compose=DmwnWrRlQzCVMtGBtZmJgFHHnqdhqpvKlsNCBxWRcDGrBHJfGvJjjmXKtKrrLWkzlFBWBDKqCWFl" target="_blank" rel="noreferrer">Contact</a>
          </li>
          <li>
          </li>
        </ul>
        </nav>
        </div>
        {/* --- End of Nav Bar--- */}
        <div className='relative'>
        {/* <img className = 'w-200 h-170 relative top-20 left-20' src='intro.png'></img> */}
        <img className=' relative mx-auto' src='intro.png'></img>
        </div>
        <div className = "text-3xl flex  justify-center gap-10 py-25  text-csumb ">
        <a href='https://github.com/Vizsla1'><AiFillGithub className='relative left-4'/></a>
        <a href='https://www.linkedin.com/in/angel-medina-6439a0252/'><AiFillLinkedin className='relative left-5'/></a>
        <a href='https://mail.google.com/mail/u/0/#inbox?compose=DmwnWrRlQzCVMtGBtZmJgFHHnqdhqpvKlsNCBxWRcDGrBHJfGvJjjmXKtKrrLWkzlFBWBDKqCWFl'><AiOutlineMail className='relative left-8'/></a>

<div class="relative justify-center items-center">
 </div>
</div>
</section>
        
        <section>

{/* ---Experience--- */}
<div className="relative justify-center flex items-center ">
  <h1 className='relative text-cool-white dark:hover:bg-csumb cursor-default dark:hover:text-cool-white items-center text-center border-2 hover:border-2 text-2xl m-16 bg-csumb w-40 border-csumb rounded-md p-1 hover:bg-cool-white group-hover:text-white duration-500 hover:text-csumb hover:border-csumb'>Experience</h1>
</div>

<div className='relative justify-center cursor-default flex p-1 hover: cool-white' >
<div className='group relative top-15 justify-center flex p-1 hover: text-cool-white group-hover:text-cool-white' >
<a href="#" className=" hover:bg-white dark:hover:bg-csumb max-w-sm dark:bg-csumb p-5 m-5 border-4  bg-csumb border-csumb rounded-lg duration-500">
    <h5 class= "text-cool-white group-hover:text-csumb dark:text-cool-white dark:group-hover:text-cool-white text-center mb-2 text-2xl font-bold tracking-tight text-csumb ">Tools</h5>
    <p class="text-cool-white group-hover:text-csumb dark:text-cool-white dark:group-hover:text-cool-white duration-1000	text-center font-medium text-csumb">HTML, CSS, React, javascript, Tailwind, Figma, NodeJS and Java</p>
</a>
</div>
<div className='group relative top-15 cursor-defaultjustify-center flex p-1 hover: text-cool-white' >
<a href="#" className="  hover:bg-white dark:hover:bg-csumb max-w-sm dark:bg-csumb p-5 m-5 border-4  bg-csumb border-csumb rounded-lg duration-500">
    <h5 class="text-cool-white group-hover:text-csumb dark:text-white duration-700 dark:group-hover:text-cool-white	text-center mb-2 text-2xl font-bold tracking-tight text-csumb ">Freshman</h5>
    <p class="text-cool-white group-hover:text-csumb dark:text-white duration-1000 dark:group-hover:text-cool-white	text-center font-medium text-csumb">Current Freshman at CSUMB. I graduate in May 2026</p>
</a>
</div>
<div className='group relative top-15 cursor-default justify-center flex p-1 hover: text-cool-white group-hover:text-cool-white' >
<a href="#" className=" hover:bg-white dark:hover:bg-csumb max-w-sm dark:bg-csumb p-5 m-5 border-4  bg-csumb border-csumb rounded-lg duration-500">
    <h5 class="text-cool-white group-hover:text-csumb dark:text-white duration-700 dark:group-hover:text-cool-white	text-center mb-2 text-2xl font-bold tracking-tight text-csumb ">1 Project</h5>
    <p class="text-cool-white group-hover:text-csumb dark:text-white duration-1000 dark:group-hover:text-cool-white	text-center font-medium text-csumb">I coded my personal portfolio website using react and tailwind. </p>
</a>
</div>
</div>
{/* ---End of Experience--- */}




{/* ---Projects--- */}
<div className='grid relative px-5 grid-cols-1 top-15 hover: text-cool-white' >
<div className="relative justify-center flex items-center ">
  <h1 className='relative text-white top-5 items-center cursor-default text-center border-2 hover:border-2 text-2xl m-16 bg-csumb w-40 border-csumb rounded-md p-1 hover:bg-white duration-500 dark:hover:bg-csumb dark:hover:text-cool-white hover:text-csumb hover:border-csumb'>Projects</h1>
</div>
<div className="relative grid justify-center ">
  <a href="#" className="group relative dark:bg-csumb p-10 pr-20 m-7 border-4 bg-csumb border-csumb rounded-lg duration-500 bg-cool-white border-csumb hover:bg-cool-white  ">
  <h1 className='bg-cool-white text-csumb group-hover:text-white group-hover:bg-csumb  group-hover:text-cool-white group-hover:bg-csumb absolute w-16 text-3xl text-center rounded  p-3 duration-700'>1</h1>
{/* <h1 className='relative text-csumb  place-self-end'>Developed in 2023</h1> */}
  <h5 class="text-cool-white  dark:text-white dark:text-white duration-1000 dark:group-hover:text-cool-white relative left-20 duration-700	text-start mb-2 text-2xl font-bold group-hover:text-csumb tracking-tight text-csumb ">Project 1</h5>
  <p class=" text-cool-white dark:text-white dark:text-white duration-1000 dark:group-hover:text-cool-white relative left-20 duration-1000	text-start font-medium text-csumb group-hover:text-csumb">Filler for future projects I will work on</p>
</a>

<a href="#" className="group relative dark:bg-csumb p-10 pr-24 m-7 border-4 bg-csumb border-csumb rounded-lg duration-500 bg-cool-white border-csumb hover:bg-cool-white ">
  <h1 className='bg-cool-white text-csumb group-hover:text-white group-hover:bg-csumb  group-hover:text-cool-white group-hover:bg-csumb absolute w-16 text-3xl text-center rounded  p-3 duration-700'>2</h1>
{/* <h1 className='absolute text-csumb justify-end'>Developed in 2023</h1> */}
  <h5 class="text-cool-white  dark:text-white relative dark:text-white duration-1000 dark:group-hover:text-cool-white left-20 duration-700	text-start mb-2 text-2xl font-bold group-hover:text-csumb tracking-tight text-csumb ">Project 2</h5>
  <p class="text-cool-white dark:text-white relative dark:text-white duration-1000 dark:group-hover:text-cool-white left-20 duration-1000	text-start font-medium text-csumb group-hover:text-csumb">Filler for future projects I will work on</p>
</a>

<a href="#" className="group relative dark:bg-csumb dark:text-white duration-1000 dark:group-hover:text-cool-white p-10 pr-20 m-7 border-4 bg-csumb border-csumb rounded-lg duration-500 bg-cool-white border-csumb hover:bg-cool-white ">
  <h1 className='bg-cool-white text-csumb group-hover:text-white group-hover:bg-csumb dark:bg-cool-white duration-1000 dark:group-hover:text-cool-white  group-hover:text-cool-white group-hover:bg-csumb absolute w-16 text-3xl text-center rounded p-3 duration-700'>3</h1>
{/* <h1 className='absolute text-csumb justify-end'>Developed in 2023</h1> */}
  <h5 class="text-cool-white  dark:text-white relative dark:text-white duration-1000 dark:group-hover:text-cool-white left-20 duration-700	text-start mb-2 text-2xl font-bold group-hover:text-csumb tracking-tight text-csumb ">Project 3</h5>
  <p class="text-cool-white dark:text-white relative dark:text-white duration-1000 dark:group-hover:text-cool-white left-20 duration-1000	text-start font-medium text-csumb group-hover:text-csumb">Filler for future projects I will work on</p>
</a>

</div>
</div>
{/* ---End of Projects --- */}


</section>
</main>
</div>
  )
}
